### ISSUE TITLE
Should have a makefile

### ISSUE THREAD

**Issue by GrantSeltzer** [stephen679/predev#1]

**Comment by GrantSeltzer** [comment]
Would not fix

**Comment by stephen679** [comment]
dang still haven't fixed this

**Comment by GrantSeltzer** [comment]
Have you tried turning it off and on again?

**Comment by GrantSeltzer** [comment]
May need to refactor in Prolog

**Comment by stephen679** [comment]
trying to golint the repo nothing is working

**Comment by GrantSeltzer** [comment]
Upside down, your avatar is a frowning face with a goatee

**Comment by GrantSeltzer** [comment]
*mic dropped*
